#!/usr/bin/R
library("openair")
ae <- read.csv(file="AEcombined20171205.csv",header=TRUE,sep=",")
ae$date <- as.POSIXct(ae$date,format="%Y-%m-%d %H:%M:%S",tz="GMT")
ae <- subset(ae,select=c("date","bc6","bb6","K6","AE470950","stn"))
sonic <- read.csv(file="sat171205WindData.csv",header=TRUE,sep=",")
sonic$date <- as.POSIXct(sonic$date,format="%Y-%m-%d %H:%M:%S",tz="GMT")
sonic <- subset(sonic,select=c("date","ws","wd"))
sat <- merge(ae,sonic,by="date")
sat$day <- as.Date(sat$date)
head(sat)
sat$year <- as.numeric(format(sat$date, format = "%Y"))
sat$month <- as.numeric(format(sat$date, format = "%m"))
sat$day <- as.numeric(format(sat$date, format = "%d"))
sat$hour <- as.numeric(format(sat$date, format = "%H"))
sat$minute <- as.numeric(format(sat$date, format = "%M"))
sat$second <- as.numeric(format(sat$date, format = "%S"))
satfinal <- subset(sat,select=c('year','month','day','hour','minute','second',"bc6","bb6","K6","AE470950","ws","wd"))
############
write.csv(satfinal,file='AEcombined20171205.csv',row.names=FALSE)
quit()
